include "src/head.asm"
include "src/main.asm"
include "src/pads.asm"
include "src/player.asm"
include "src/apples.asm"
include "src/prng.asm"
include "src/tables.asm"
include "src/vectors.asm"

.incbin "src/tileset.chr"
